source 'https://github.com/CocoaPods/Specs.git'

target 'TCTableViewSearchController', :exclusive => true do
  pod "TCTableViewSearchController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TCTableViewSearchController", :path => "../"

  
end
